-- Aug-2026 issues 20 & 21 — the evaluation report needs real PER-EVALUATOR,
-- PER-PARAMETER human scores, not just the roll-up totals seeded in 0008.
--
-- Issue 20: "additional columns keep adding as the deck passes hands" — each
-- evaluator below becomes a column on the report.
-- Issue 21: the hierarchy (program associate → jury → program manager) is only
-- observable once more than one level has scored the same deck, so each deck
-- here carries scores from all three levels.
--
-- Values are derived from the evaluator's own weighted total already in
-- `evaluations` (0008), spread deterministically across the parameters, so the
-- per-parameter detail agrees with the totals the reports already show.

DELETE FROM scores WHERE evaluator_kind = 'human' AND deck_id IN (
  'inc_deck_insureflow','inc_deck_greengrid','inc_deck_finstack',
  'inc_deck_wealthosi','inc_deck_greenroute'
);

INSERT INTO scores (id, deck_id, evaluator_id, evaluator_kind, parameter_id, value, comment) VALUES
  ('hs_3127a2', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_problem_market_clarity', 9.5, 'Well evidenced in the materials.'),
  ('hs_9bdaa6', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_solution_value_prop', 8.0, 'Well evidenced in the materials.'),
  ('hs_b527d3', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_market_size', 9.5, 'Some concern; worth probing on the call.'),
  ('hs_9321cd', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_product_technology', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_4adddb', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_business_model', 7.0, 'Meets the bar for this cohort.'),
  ('hs_0bfe13', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_traction_validation', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_c5a7fa', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_competitive_landscape', 9.0, 'Clear positive, consistent with the mandate.'),
  ('hs_de5fe3', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_gtm_strategy', 9.5, 'Meets the bar for this cohort.'),
  ('hs_8f47a7', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_team_execution', 8.5, 'Mixed read; only partially addressed.'),
  ('hs_8ed236', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_business_risks', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_36fc9c', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_business_attractiveness', 7.0, 'Clear positive, consistent with the mandate.'),
  ('hs_3b4e91', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_climate_impact', 8.5, 'Some concern; worth probing on the call.'),
  ('hs_88bc2d', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_storytelling', 9.5, 'Some concern; worth probing on the call.'),
  ('hs_5101d3', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_add_jury_1', 8.5, 'Mixed read; only partially addressed.'),
  ('hs_5101d4', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_add_jury_2', 8.5, 'Well evidenced in the materials.'),
  ('hs_5101d5', 'inc_deck_insureflow', 'inc_jury', 'human', 'inc_add_jury_3', 8.5, 'Meets the bar for this cohort.'),
  ('hs_d5008d', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_problem_market_clarity', 8.5, 'Meets the bar for this cohort.'),
  ('hs_49a19b', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_solution_value_prop', 7.0, 'Some concern; worth probing on the call.'),
  ('hs_9fb3c8', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_market_size', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_462838', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_product_technology', 7.0, 'Well evidenced in the materials.'),
  ('hs_bfd1c6', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_business_model', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_b9c508', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_traction_validation', 8.5, 'Well evidenced in the materials.'),
  ('hs_1d85af', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_competitive_landscape', 8.0, 'Meets the bar for this cohort.'),
  ('hs_45528e', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_gtm_strategy', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_043b92', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_team_execution', 7.5, 'Clear positive, consistent with the mandate.'),
  ('hs_03c621', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_business_risks', 9.5, 'Mixed read; only partially addressed.'),
  ('hs_0e4111', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_business_attractiveness', 6.5, 'Some concern; worth probing on the call.'),
  ('hs_b0427c', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_climate_impact', 7.0, 'Clear positive, consistent with the mandate.'),
  ('hs_efaed8', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_storytelling', 9.0, 'Clear positive, consistent with the mandate.'),
  ('hs_35a429', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_add_pm_1', 9.0, 'Meets the bar for this cohort.'),
  ('hs_35a42a', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_add_pm_2', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_35a42b', 'inc_deck_insureflow', 'inc_pm', 'human', 'inc_add_pm_3', 7.0, 'Some concern; worth probing on the call.'),
  ('hs_083781', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_problem_market_clarity', 8.0, 'Meets the bar for this cohort.'),
  ('hs_36ef27', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_solution_value_prop', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_c94d54', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_market_size', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_f2f92c', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_product_technology', 7.0, 'Well evidenced in the materials.'),
  ('hs_c33cba', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_business_model', 7.5, 'Clear positive, consistent with the mandate.'),
  ('hs_a71294', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_traction_validation', 9.5, 'Clear positive, consistent with the mandate.'),
  ('hs_eda03b', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_competitive_landscape', 9.0, 'Meets the bar for this cohort.'),
  ('hs_4eea82', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_gtm_strategy', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_07a686', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_team_execution', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_073115', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_business_risks', 8.0, 'Meets the bar for this cohort.'),
  ('hs_41e89d', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_business_attractiveness', 7.0, 'Mixed read; only partially addressed.'),
  ('hs_b3ad70', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_climate_impact', 9.0, 'Well evidenced in the materials.'),
  ('hs_f946cc', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_storytelling', 9.0, 'Clear positive, consistent with the mandate.'),
  ('hs_112911', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_add_pa_1', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_112912', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_add_pa_2', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_112913', 'inc_deck_insureflow', 'inc_pa', 'human', 'inc_add_pa_3', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_8fff39', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_problem_market_clarity', 7.5, 'Some concern; worth probing on the call.'),
  ('hs_f3026f', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_solution_value_prop', 10.0, 'Meets the bar for this cohort.'),
  ('hs_51289c', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_market_size', 7.5, 'Well evidenced in the materials.'),
  ('hs_435ce4', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_product_technology', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_8a3c72', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_business_model', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_6325dc', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_traction_validation', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_f20183', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_competitive_landscape', 7.5, 'Meets the bar for this cohort.'),
  ('hs_c2783a', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_gtm_strategy', 9.5, 'Clear positive, consistent with the mandate.'),
  ('hs_cea63e', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_team_execution', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_ce30cd', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_business_risks', 10.0, 'Mixed read; only partially addressed.'),
  ('hs_b317e5', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_business_attractiveness', 10.0, 'Mixed read; only partially addressed.'),
  ('hs_7aad28', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_climate_impact', 7.5, 'Clear positive, consistent with the mandate.'),
  ('hs_6cd484', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_storytelling', 10.0, 'Clear positive, consistent with the mandate.'),
  ('hs_3d43ea', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_add_jury_1', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_3d43eb', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_add_jury_2', 8.5, 'Mixed read; only partially addressed.'),
  ('hs_3d43ec', 'inc_deck_greengrid', 'inc_jury', 'human', 'inc_add_jury_3', 9.0, 'Well evidenced in the materials.'),
  ('hs_62d1e4', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_problem_market_clarity', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_aa27a4', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_solution_value_prop', 7.5, 'Adequate — a couple of open questions remain.'),
  ('hs_a752d1', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_market_size', 9.0, 'Meets the bar for this cohort.'),
  ('hs_283d0f', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_product_technology', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_a3ea1d', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_business_model', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_1a4b11', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_traction_validation', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_74ad78', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_competitive_landscape', 7.5, 'Well evidenced in the materials.'),
  ('hs_3194a5', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_gtm_strategy', 9.5, 'Some concern; worth probing on the call.'),
  ('hs_e853e9', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_team_execution', 7.5, 'Meets the bar for this cohort.'),
  ('hs_e7de78', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_business_risks', 10.0, 'Well evidenced in the materials.'),
  ('hs_3a9a9a', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_business_attractiveness', 8.5, 'Well evidenced in the materials.'),
  ('hs_945ad3', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_climate_impact', 7.5, 'Mixed read; only partially addressed.'),
  ('hs_dbf0ef', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_storytelling', 10.0, 'Some concern; worth probing on the call.'),
  ('hs_cc89c0', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_add_pm_1', 10.0, 'Adequate — a couple of open questions remain.'),
  ('hs_cc89c1', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_add_pm_2', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_cc89c2', 'inc_deck_greengrid', 'inc_pm', 'human', 'inc_add_pm_3', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_9608d8', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_problem_market_clarity', 7.5, 'Clear positive, consistent with the mandate.'),
  ('hs_977530', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_solution_value_prop', 8.0, 'Adequate — a couple of open questions remain.'),
  ('hs_d0ec5d', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_market_size', 9.5, 'Mixed read; only partially addressed.'),
  ('hs_d50e03', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_product_technology', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_a75511', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_business_model', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_07989d', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_traction_validation', 9.5, 'Some concern; worth probing on the call.'),
  ('hs_44c804', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_competitive_landscape', 8.5, 'Well evidenced in the materials.'),
  ('hs_3b2c99', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_gtm_strategy', 9.5, 'Some concern; worth probing on the call.'),
  ('hs_ebbedd', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_team_execution', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_eb496c', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_business_risks', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_6e4226', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_business_attractiveness', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_97c5c7', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_climate_impact', 9.5, 'Meets the bar for this cohort.'),
  ('hs_e588e3', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_storytelling', 10.0, 'Some concern; worth probing on the call.'),
  ('hs_a80ea8', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_add_pa_1', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_a80ea9', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_add_pa_2', 9.0, 'Mixed read; only partially addressed.'),
  ('hs_a80eaa', 'inc_deck_greengrid', 'inc_pa', 'human', 'inc_add_pa_3', 9.0, 'Well evidenced in the materials.'),
  ('hs_482617', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_problem_market_clarity', 8.0, 'Meets the bar for this cohort.'),
  ('hs_117851', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_solution_value_prop', 9.5, 'Meets the bar for this cohort.'),
  ('hs_6ca07e', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_market_size', 7.0, 'Well evidenced in the materials.'),
  ('hs_6da2c2', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_product_technology', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_0e2150', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_business_model', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_819bbe', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_traction_validation', 8.0, 'Adequate — a couple of open questions remain.'),
  ('hs_4a86e5', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_competitive_landscape', 9.5, 'Mixed read; only partially addressed.'),
  ('hs_15fc98', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_gtm_strategy', 7.5, 'Well evidenced in the materials.'),
  ('hs_528b1c', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_team_execution', 9.5, 'Adequate — a couple of open questions remain.'),
  ('hs_5215ab', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_business_risks', 9.0, 'Meets the bar for this cohort.'),
  ('hs_ffccc7', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_business_attractiveness', 9.5, 'Meets the bar for this cohort.'),
  ('hs_fe9206', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_climate_impact', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_c058e2', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_storytelling', 7.5, 'Adequate — a couple of open questions remain.'),
  ('hs_c247c8', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_add_jury_1', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_c247c9', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_add_jury_2', 8.5, 'Some concern; worth probing on the call.'),
  ('hs_c247ca', 'inc_deck_finstack', 'inc_jury', 'human', 'inc_add_jury_3', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_131842', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_problem_market_clarity', 9.5, 'Well evidenced in the materials.'),
  ('hs_50ae06', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_solution_value_prop', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_a35b33', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_market_size', 7.0, 'Some concern; worth probing on the call.'),
  ('hs_46626d', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_product_technology', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_f76e7b', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_business_model', 9.5, 'Meets the bar for this cohort.'),
  ('hs_c0d173', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_traction_validation', 6.5, 'Mixed read; only partially addressed.'),
  ('hs_93235a', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_competitive_landscape', 7.0, 'Well evidenced in the materials.'),
  ('hs_b69883', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_gtm_strategy', 9.0, 'Meets the bar for this cohort.'),
  ('hs_3bd847', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_team_execution', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_3b62d6', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_business_risks', 7.0, 'Clear positive, consistent with the mandate.'),
  ('hs_931ffc', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_business_attractiveness', 7.0, 'Clear positive, consistent with the mandate.'),
  ('hs_e7df31', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_climate_impact', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_60f4cd', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_storytelling', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_ba2c9e', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_add_pm_1', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_ba2c9f', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_add_pm_2', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_ba2ca0', 'inc_deck_finstack', 'inc_pm', 'human', 'inc_add_pm_3', 8.0, 'Well evidenced in the materials.'),
  ('hs_464f36', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_problem_market_clarity', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_3dfb92', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_solution_value_prop', 9.5, 'Adequate — a couple of open questions remain.'),
  ('hs_ccf4bf', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_market_size', 8.0, 'Meets the bar for this cohort.'),
  ('hs_f33361', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_product_technology', 8.5, 'Some concern; worth probing on the call.'),
  ('hs_fad96f', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_business_model', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_ae1eff', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_traction_validation', 7.5, 'Mixed read; only partially addressed.'),
  ('hs_633de6', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_competitive_landscape', 7.5, 'Adequate — a couple of open questions remain.'),
  ('hs_c03077', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_gtm_strategy', 9.0, 'Meets the bar for this cohort.'),
  ('hs_3f433b', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_team_execution', 6.5, 'Meets the bar for this cohort.'),
  ('hs_3ecdca', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_business_risks', 9.0, 'Well evidenced in the materials.'),
  ('hs_c6c788', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_business_attractiveness', 7.0, 'Adequate — a couple of open questions remain.'),
  ('hs_eb4a25', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_climate_impact', 6.5, 'Mixed read; only partially addressed.'),
  ('hs_6a8cc1', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_storytelling', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_95b186', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_add_pa_1', 7.0, 'Well evidenced in the materials.'),
  ('hs_95b187', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_add_pa_2', 7.0, 'Meets the bar for this cohort.'),
  ('hs_95b188', 'inc_deck_finstack', 'inc_pa', 'human', 'inc_add_pa_3', 7.0, 'Adequate — a couple of open questions remain.'),
  ('hs_e902e8', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_problem_market_clarity', 6.0, 'Well evidenced in the materials.'),
  ('hs_653520', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_solution_value_prop', 6.5, 'Adequate — a couple of open questions remain.'),
  ('hs_959c4d', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_market_size', 6.0, 'Meets the bar for this cohort.'),
  ('hs_579013', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_product_technology', 6.5, 'Some concern; worth probing on the call.'),
  ('hs_5d5f21', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_business_model', 6.5, 'Mixed read; only partially addressed.'),
  ('hs_d5588d', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_traction_validation', 7.5, 'Mixed read; only partially addressed.'),
  ('hs_a24bf4', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_competitive_landscape', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_0c7aa9', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_gtm_strategy', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_a1c8ed', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_team_execution', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_a1537c', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_business_risks', 7.0, 'Adequate — a couple of open questions remain.'),
  ('hs_7a8a16', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_business_attractiveness', 7.5, 'Clear positive, consistent with the mandate.'),
  ('hs_4dcfd7', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_climate_impact', 8.0, 'Meets the bar for this cohort.'),
  ('hs_b6d6f3', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_storytelling', 8.5, 'Meets the bar for this cohort.'),
  ('hs_b31619', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_add_jury_1', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_b3161a', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_add_jury_2', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_b3161b', 'inc_deck_wealthosi', 'inc_jury', 'human', 'inc_add_jury_3', 8.5, 'Mixed read; only partially addressed.'),
  ('hs_36f553', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_problem_market_clarity', 7.5, 'Some concern; worth probing on the call.'),
  ('hs_bb5295', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_solution_value_prop', 7.5, 'Mixed read; only partially addressed.'),
  ('hs_26fec2', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_market_size', 6.5, 'Well evidenced in the materials.'),
  ('hs_bd6ffe', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_product_technology', 8.0, 'Well evidenced in the materials.'),
  ('hs_edec8c', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_business_model', 7.5, 'Well evidenced in the materials.'),
  ('hs_2b7602', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_traction_validation', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_e6e029', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_competitive_landscape', 6.5, 'Some concern; worth probing on the call.'),
  ('hs_a766d4', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_gtm_strategy', 8.0, 'Adequate — a couple of open questions remain.'),
  ('hs_325658', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_team_execution', 5.5, 'Clear positive, consistent with the mandate.'),
  ('hs_31e0e7', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_business_risks', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_eae50b', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_business_attractiveness', 6.0, 'Some concern; worth probing on the call.'),
  ('hs_de5d42', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_climate_impact', 5.5, 'Adequate — a couple of open questions remain.'),
  ('hs_51c31e', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_storytelling', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_a8cb6f', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_add_pm_1', 7.5, 'Meets the bar for this cohort.'),
  ('hs_a8cb70', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_add_pm_2', 7.5, 'Adequate — a couple of open questions remain.'),
  ('hs_a8cb71', 'inc_deck_wealthosi', 'inc_pm', 'human', 'inc_add_pm_3', 7.5, 'Some concern; worth probing on the call.'),
  ('hs_6a2c47', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_problem_market_clarity', 7.0, 'Some concern; worth probing on the call.'),
  ('hs_a8a021', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_solution_value_prop', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_50984e', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_market_size', 7.0, 'Well evidenced in the materials.'),
  ('hs_6a40f2', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_product_technology', 7.5, 'Well evidenced in the materials.'),
  ('hs_f15780', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_business_model', 6.0, 'Adequate — a couple of open questions remain.'),
  ('hs_18c38e', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_traction_validation', 6.0, 'Well evidenced in the materials.'),
  ('hs_b6fab5', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_competitive_landscape', 7.5, 'Some concern; worth probing on the call.'),
  ('hs_b0fec8', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_gtm_strategy', 8.0, 'Adequate — a couple of open questions remain.'),
  ('hs_35c14c', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_team_execution', 7.0, 'Well evidenced in the materials.'),
  ('hs_354bdb', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_business_risks', 6.5, 'Mixed read; only partially addressed.'),
  ('hs_1e8c97', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_business_attractiveness', 6.5, 'Mixed read; only partially addressed.'),
  ('hs_e1c836', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_climate_impact', 7.5, 'Clear positive, consistent with the mandate.'),
  ('hs_5b5b12', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_storytelling', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_845057', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_add_pa_1', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_845058', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_add_pa_2', 6.0, 'Well evidenced in the materials.'),
  ('hs_845059', 'inc_deck_wealthosi', 'inc_pa', 'human', 'inc_add_pa_3', 6.0, 'Meets the bar for this cohort.'),
  ('hs_33d260', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_problem_market_clarity', 9.5, 'Well evidenced in the materials.'),
  ('hs_c158a8', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_solution_value_prop', 9.5, 'Adequate — a couple of open questions remain.'),
  ('hs_f1c7d5', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_market_size', 9.0, 'Some concern; worth probing on the call.'),
  ('hs_a4db8b', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_product_technology', 8.5, 'Some concern; worth probing on the call.'),
  ('hs_4b2699', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_business_model', 9.5, 'Mixed read; only partially addressed.'),
  ('hs_317c15', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_traction_validation', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_83ad7c', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_competitive_landscape', 7.5, 'Well evidenced in the materials.'),
  ('hs_35c021', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_gtm_strategy', 7.5, 'Meets the bar for this cohort.'),
  ('hs_8f9065', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_team_execution', 7.5, 'Some concern; worth probing on the call.'),
  ('hs_8f1af4', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_business_risks', 7.0, 'Adequate — a couple of open questions remain.'),
  ('hs_89a99e', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_business_attractiveness', 8.0, 'Adequate — a couple of open questions remain.'),
  ('hs_3b974f', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_climate_impact', 8.0, 'Meets the bar for this cohort.'),
  ('hs_e01c6b', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_storytelling', 8.0, 'Meets the bar for this cohort.'),
  ('hs_df5991', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_add_jury_1', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_df5992', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_add_jury_2', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_df5993', 'inc_deck_greenroute', 'inc_jury', 'human', 'inc_add_jury_3', 8.5, 'Mixed read; only partially addressed.'),
  ('hs_5f42cb', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_problem_market_clarity', 9.0, 'Mixed read; only partially addressed.'),
  ('hs_5ab81d', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_solution_value_prop', 9.0, 'Meets the bar for this cohort.'),
  ('hs_286c4a', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_market_size', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_573976', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_product_technology', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_173204', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_business_model', 7.0, 'Well evidenced in the materials.'),
  ('hs_cadb8a', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_traction_validation', 7.5, 'Adequate — a couple of open questions remain.'),
  ('hs_4303b1', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_competitive_landscape', 7.0, 'Meets the bar for this cohort.'),
  ('hs_d3aa4c', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_gtm_strategy', 9.0, 'Well evidenced in the materials.'),
  ('hs_5b9bd0', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_team_execution', 8.5, 'Clear positive, consistent with the mandate.'),
  ('hs_5b265f', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_business_risks', 8.0, 'Some concern; worth probing on the call.'),
  ('hs_cc4693', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_business_attractiveness', 8.5, 'Mixed read; only partially addressed.'),
  ('hs_07a2ba', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_climate_impact', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_7e0696', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_storytelling', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_b18ae7', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_add_pm_1', 7.5, 'Some concern; worth probing on the call.'),
  ('hs_b18ae8', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_add_pm_2', 8.0, 'Clear positive, consistent with the mandate.'),
  ('hs_b18ae9', 'inc_deck_greenroute', 'inc_pm', 'human', 'inc_add_pm_3', 8.0, 'Mixed read; only partially addressed.'),
  ('hs_9279bf', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_problem_market_clarity', 8.0, 'Meets the bar for this cohort.'),
  ('hs_4805a9', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_solution_value_prop', 6.5, 'Mixed read; only partially addressed.'),
  ('hs_5205d6', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_market_size', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_040a6a', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_product_technology', 7.5, 'Clear positive, consistent with the mandate.'),
  ('hs_1a9cf8', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_business_model', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_b82916', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_traction_validation', 8.0, 'Adequate — a couple of open questions remain.'),
  ('hs_131e3d', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_competitive_landscape', 8.0, 'Meets the bar for this cohort.'),
  ('hs_dd4240', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_gtm_strategy', 9.0, 'Well evidenced in the materials.'),
  ('hs_5f06c4', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_team_execution', 7.0, 'Well evidenced in the materials.'),
  ('hs_5e9153', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_business_risks', 6.5, 'Mixed read; only partially addressed.'),
  ('hs_ffee1f', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_business_attractiveness', 8.5, 'Meets the bar for this cohort.'),
  ('hs_0b0dae', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_climate_impact', 7.0, 'Well evidenced in the materials.'),
  ('hs_879e8a', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_storytelling', 9.0, 'Adequate — a couple of open questions remain.'),
  ('hs_8d0fcf', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_add_pa_1', 8.0, 'Meets the bar for this cohort.'),
  ('hs_8d0fd0', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_add_pa_2', 8.5, 'Adequate — a couple of open questions remain.'),
  ('hs_8d0fd1', 'inc_deck_greenroute', 'inc_pa', 'human', 'inc_add_pa_3', 8.5, 'Some concern; worth probing on the call.');

-- Keep the roll-up in `evaluations` in agreement with the per-parameter detail
-- above for the two decks 0008 did not cover, so the Jury Pipeline's "Jury
-- score" and "Avg. score" columns match the report a reviewer opens from them.
DELETE FROM evaluations
WHERE evaluator_id IS NOT NULL AND deck_id IN ('inc_deck_wealthosi', 'inc_deck_greenroute');

INSERT INTO evaluations (id, deck_id, evaluator_id, weighted_total, verdict, remarks, submitted_at)
SELECT 'ev_seed_' || s.deck_id || '_' || s.evaluator_id,
       s.deck_id,
       s.evaluator_id,
       ROUND(SUM(s.value * p.weight) / SUM(p.weight), 1),
       'advanced',
       'Evaluation submitted',
       '2026-08-21T07:00:00Z'
FROM scores s
JOIN parameters p ON p.id = s.parameter_id
WHERE s.evaluator_kind = 'human'
  AND p.informational = 0
  AND s.deck_id IN ('inc_deck_wealthosi', 'inc_deck_greenroute')
GROUP BY s.deck_id, s.evaluator_id;
