-- W1-B · migration 4 of 13 (0025 – 0037).
--
-- Admin console → Evaluation → **Clarification question bank**
-- (`admin/s-qb.html`): "These questions are auto-triggered to the startup when
-- the AI detects weak, missing, or contradictory signal in a given area.
-- Replicated from the BRD; edit or add questions per area."
--
-- 68 curated questions per edition — five for each of the 13 evaluation areas
-- except **Climate Impact & Integrity, which has eight**. The two Super User
-- builds carry byte-identical question text, so both editions seed the same
-- set; they diverge the moment an org edits one, which is why the rows are
-- keyed to `parameters.id` (edition-scoped) rather than to a shared area key.
--
-- Today `src/shared/queries.ts` generates a clarification email from a bullet
-- list of area LABELS. W2-C wires this bank in behind it.

CREATE TABLE IF NOT EXISTS question_bank (
  id           TEXT PRIMARY KEY,
  parameter_id TEXT NOT NULL REFERENCES parameters (id) ON DELETE CASCADE,
  -- Display / Q-number order within the area. Not unique: reordering swaps them.
  seq          INTEGER NOT NULL,
  text         TEXT NOT NULL,
  active       INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_question_bank_param ON question_bank (parameter_id, seq);

INSERT INTO question_bank (id, parameter_id, seq, text) VALUES
  ('qb_inc_problem_market_clarity_1', 'inc_problem_market_clarity', 1, 'Who is the primary customer facing this problem?'),
  ('qb_inc_problem_market_clarity_2', 'inc_problem_market_clarity', 2, 'How frequently does this problem occur?'),
  ('qb_inc_problem_market_clarity_3', 'inc_problem_market_clarity', 3, 'What happens if this problem is not solved?'),
  ('qb_inc_problem_market_clarity_4', 'inc_problem_market_clarity', 4, 'How are customers solving this today?'),
  ('qb_inc_problem_market_clarity_5', 'inc_problem_market_clarity', 5, 'What evidence do you have that this is a real pain point?'),
  ('qb_inc_solution_value_prop_1', 'inc_solution_value_prop', 1, 'How exactly does your solution solve the problem differently from existing options?'),
  ('qb_inc_solution_value_prop_2', 'inc_solution_value_prop', 2, 'What is the single most important benefit you deliver?'),
  ('qb_inc_solution_value_prop_3', 'inc_solution_value_prop', 3, 'Which customer workflow changes because of your solution?'),
  ('qb_inc_solution_value_prop_4', 'inc_solution_value_prop', 4, 'What alternatives did customers try before choosing you?'),
  ('qb_inc_solution_value_prop_5', 'inc_solution_value_prop', 5, 'What would customers lose if your solution disappeared tomorrow?'),
  ('qb_inc_market_size_1', 'inc_market_size', 1, 'How did you calculate your TAM? Is it bottom-up?'),
  ('qb_inc_market_size_2', 'inc_market_size', 2, 'Who is not a customer in your TAM?'),
  ('qb_inc_market_size_3', 'inc_market_size', 3, 'What is your initial beachhead market?'),
  ('qb_inc_market_size_4', 'inc_market_size', 4, 'How does your market expand over time?'),
  ('qb_inc_market_size_5', 'inc_market_size', 5, 'What assumptions would make this market smaller than expected?'),
  ('qb_inc_product_technology_1', 'inc_product_technology', 1, 'What exists today vs what is still planned?'),
  ('qb_inc_product_technology_2', 'inc_product_technology', 2, 'What is the hardest technical problem you have already solved?'),
  ('qb_inc_product_technology_3', 'inc_product_technology', 3, 'What would break first at 10× scale?'),
  ('qb_inc_product_technology_4', 'inc_product_technology', 4, 'What third-party technologies do you depend on?'),
  ('qb_inc_product_technology_5', 'inc_product_technology', 5, 'What cannot be easily replicated by competitors?'),
  ('qb_inc_business_model_1', 'inc_business_model', 1, 'Who pays you and for what?'),
  ('qb_inc_business_model_2', 'inc_business_model', 2, 'How is pricing determined?'),
  ('qb_inc_business_model_3', 'inc_business_model', 3, 'What are your largest cost drivers?'),
  ('qb_inc_business_model_4', 'inc_business_model', 4, 'What needs to be true for this business to become profitable?'),
  ('qb_inc_business_model_5', 'inc_business_model', 5, 'How do unit economics improve with scale?'),
  ('qb_inc_traction_validation_1', 'inc_traction_validation', 1, 'What is your strongest proof of customer demand?'),
  ('qb_inc_traction_validation_2', 'inc_traction_validation', 2, 'How many paying customers do you have today?'),
  ('qb_inc_traction_validation_3', 'inc_traction_validation', 3, 'What has grown fastest in the last 6 months?'),
  ('qb_inc_traction_validation_4', 'inc_traction_validation', 4, 'What feedback caused you to change your product?'),
  ('qb_inc_traction_validation_5', 'inc_traction_validation', 5, 'Why did your earliest customers say yes?'),
  ('qb_inc_competitive_landscape_1', 'inc_competitive_landscape', 1, 'Who are customers comparing you against?'),
  ('qb_inc_competitive_landscape_2', 'inc_competitive_landscape', 2, 'Why haven’t incumbents solved this already?'),
  ('qb_inc_competitive_landscape_3', 'inc_competitive_landscape', 3, 'What do competitors do better than you today?'),
  ('qb_inc_competitive_landscape_4', 'inc_competitive_landscape', 4, 'How easy is it for a customer to switch away from you?'),
  ('qb_inc_competitive_landscape_5', 'inc_competitive_landscape', 5, 'What happens if a large incumbent copies you?'),
  ('qb_inc_gtm_strategy_1', 'inc_gtm_strategy', 1, 'How do customers first hear about you?'),
  ('qb_inc_gtm_strategy_2', 'inc_gtm_strategy', 2, 'Who is the decision-maker vs user vs buyer?'),
  ('qb_inc_gtm_strategy_3', 'inc_gtm_strategy', 3, 'What is your typical sales cycle length?'),
  ('qb_inc_gtm_strategy_4', 'inc_gtm_strategy', 4, 'Which channel has worked best so far — and why?'),
  ('qb_inc_gtm_strategy_5', 'inc_gtm_strategy', 5, 'What makes customer acquisition hard in this market?'),
  ('qb_inc_team_execution_1', 'inc_team_execution', 1, 'Why is this team uniquely suited to solve this problem?'),
  ('qb_inc_team_execution_2', 'inc_team_execution', 2, 'What key skills are currently missing on the team?'),
  ('qb_inc_team_execution_3', 'inc_team_execution', 3, 'What execution mistake did you make — and what did you learn?'),
  ('qb_inc_team_execution_4', 'inc_team_execution', 4, 'Who makes technical vs commercial decisions?'),
  ('qb_inc_team_execution_5', 'inc_team_execution', 5, 'Which advisors materially influence outcomes?'),
  ('qb_inc_business_risks_1', 'inc_business_risks', 1, 'What are the top 3 reasons this business could fail?'),
  ('qb_inc_business_risks_2', 'inc_business_risks', 2, 'What assumptions keep you up at night?'),
  ('qb_inc_business_risks_3', 'inc_business_risks', 3, 'What dependency would hurt you most if removed?'),
  ('qb_inc_business_risks_4', 'inc_business_risks', 4, 'What external factors could slow adoption?'),
  ('qb_inc_business_risks_5', 'inc_business_risks', 5, 'What risk increases as you scale?'),
  ('qb_inc_business_attractiveness_1', 'inc_business_attractiveness', 1, 'If this works, how big can it realistically become?'),
  ('qb_inc_business_attractiveness_2', 'inc_business_attractiveness', 2, 'What makes this a venture-scale opportunity?'),
  ('qb_inc_business_attractiveness_3', 'inc_business_attractiveness', 3, 'Where do margins expand over time?'),
  ('qb_inc_business_attractiveness_4', 'inc_business_attractiveness', 4, 'What strategic buyers would care about this?'),
  ('qb_inc_business_attractiveness_5', 'inc_business_attractiveness', 5, 'Why could this become a category leader?'),
  ('qb_inc_climate_impact_1', 'inc_climate_impact', 1, 'What is the baseline scenario without your solution?'),
  ('qb_inc_climate_impact_2', 'inc_climate_impact', 2, 'What specific metric defines your climate impact?'),
  ('qb_inc_climate_impact_3', 'inc_climate_impact', 3, 'Is this impact reduction, avoidance, or removal?'),
  ('qb_inc_climate_impact_4', 'inc_climate_impact', 4, 'How is impact measured and verified?'),
  ('qb_inc_climate_impact_5', 'inc_climate_impact', 5, 'Would this impact happen without you (additionality)?'),
  ('qb_inc_climate_impact_6', 'inc_climate_impact', 6, 'What assumptions drive your impact estimates?'),
  ('qb_inc_climate_impact_7', 'inc_climate_impact', 7, 'What are potential rebound or leakage effects?'),
  ('qb_inc_climate_impact_8', 'inc_climate_impact', 8, 'How does this align with net-zero or 1.5°C pathways?'),
  ('qb_inc_storytelling_1', 'inc_storytelling', 1, 'What is the one thing you want us to remember?'),
  ('qb_inc_storytelling_2', 'inc_storytelling', 2, 'Why does this matter now?'),
  ('qb_inc_storytelling_3', 'inc_storytelling', 3, 'Which slide best represents your core insight?'),
  ('qb_inc_storytelling_4', 'inc_storytelling', 4, 'What would you remove if you had 5 slides fewer?'),
  ('qb_inc_storytelling_5', 'inc_storytelling', 5, 'Where do most people misunderstand your business?'),
  ('qb_vc_problem_market_clarity_1', 'vc_problem_market_clarity', 1, 'Who is the primary customer facing this problem?'),
  ('qb_vc_problem_market_clarity_2', 'vc_problem_market_clarity', 2, 'How frequently does this problem occur?'),
  ('qb_vc_problem_market_clarity_3', 'vc_problem_market_clarity', 3, 'What happens if this problem is not solved?'),
  ('qb_vc_problem_market_clarity_4', 'vc_problem_market_clarity', 4, 'How are customers solving this today?'),
  ('qb_vc_problem_market_clarity_5', 'vc_problem_market_clarity', 5, 'What evidence do you have that this is a real pain point?'),
  ('qb_vc_solution_value_prop_1', 'vc_solution_value_prop', 1, 'How exactly does your solution solve the problem differently from existing options?'),
  ('qb_vc_solution_value_prop_2', 'vc_solution_value_prop', 2, 'What is the single most important benefit you deliver?'),
  ('qb_vc_solution_value_prop_3', 'vc_solution_value_prop', 3, 'Which customer workflow changes because of your solution?'),
  ('qb_vc_solution_value_prop_4', 'vc_solution_value_prop', 4, 'What alternatives did customers try before choosing you?'),
  ('qb_vc_solution_value_prop_5', 'vc_solution_value_prop', 5, 'What would customers lose if your solution disappeared tomorrow?'),
  ('qb_vc_market_size_1', 'vc_market_size', 1, 'How did you calculate your TAM? Is it bottom-up?'),
  ('qb_vc_market_size_2', 'vc_market_size', 2, 'Who is not a customer in your TAM?'),
  ('qb_vc_market_size_3', 'vc_market_size', 3, 'What is your initial beachhead market?'),
  ('qb_vc_market_size_4', 'vc_market_size', 4, 'How does your market expand over time?'),
  ('qb_vc_market_size_5', 'vc_market_size', 5, 'What assumptions would make this market smaller than expected?'),
  ('qb_vc_product_technology_1', 'vc_product_technology', 1, 'What exists today vs what is still planned?'),
  ('qb_vc_product_technology_2', 'vc_product_technology', 2, 'What is the hardest technical problem you have already solved?'),
  ('qb_vc_product_technology_3', 'vc_product_technology', 3, 'What would break first at 10× scale?'),
  ('qb_vc_product_technology_4', 'vc_product_technology', 4, 'What third-party technologies do you depend on?'),
  ('qb_vc_product_technology_5', 'vc_product_technology', 5, 'What cannot be easily replicated by competitors?'),
  ('qb_vc_business_model_1', 'vc_business_model', 1, 'Who pays you and for what?'),
  ('qb_vc_business_model_2', 'vc_business_model', 2, 'How is pricing determined?'),
  ('qb_vc_business_model_3', 'vc_business_model', 3, 'What are your largest cost drivers?'),
  ('qb_vc_business_model_4', 'vc_business_model', 4, 'What needs to be true for this business to become profitable?'),
  ('qb_vc_business_model_5', 'vc_business_model', 5, 'How do unit economics improve with scale?'),
  ('qb_vc_traction_validation_1', 'vc_traction_validation', 1, 'What is your strongest proof of customer demand?'),
  ('qb_vc_traction_validation_2', 'vc_traction_validation', 2, 'How many paying customers do you have today?'),
  ('qb_vc_traction_validation_3', 'vc_traction_validation', 3, 'What has grown fastest in the last 6 months?'),
  ('qb_vc_traction_validation_4', 'vc_traction_validation', 4, 'What feedback caused you to change your product?'),
  ('qb_vc_traction_validation_5', 'vc_traction_validation', 5, 'Why did your earliest customers say yes?'),
  ('qb_vc_competitive_landscape_1', 'vc_competitive_landscape', 1, 'Who are customers comparing you against?'),
  ('qb_vc_competitive_landscape_2', 'vc_competitive_landscape', 2, 'Why haven’t incumbents solved this already?'),
  ('qb_vc_competitive_landscape_3', 'vc_competitive_landscape', 3, 'What do competitors do better than you today?'),
  ('qb_vc_competitive_landscape_4', 'vc_competitive_landscape', 4, 'How easy is it for a customer to switch away from you?'),
  ('qb_vc_competitive_landscape_5', 'vc_competitive_landscape', 5, 'What happens if a large incumbent copies you?'),
  ('qb_vc_gtm_strategy_1', 'vc_gtm_strategy', 1, 'How do customers first hear about you?'),
  ('qb_vc_gtm_strategy_2', 'vc_gtm_strategy', 2, 'Who is the decision-maker vs user vs buyer?'),
  ('qb_vc_gtm_strategy_3', 'vc_gtm_strategy', 3, 'What is your typical sales cycle length?'),
  ('qb_vc_gtm_strategy_4', 'vc_gtm_strategy', 4, 'Which channel has worked best so far — and why?'),
  ('qb_vc_gtm_strategy_5', 'vc_gtm_strategy', 5, 'What makes customer acquisition hard in this market?'),
  ('qb_vc_team_execution_1', 'vc_team_execution', 1, 'Why is this team uniquely suited to solve this problem?'),
  ('qb_vc_team_execution_2', 'vc_team_execution', 2, 'What key skills are currently missing on the team?'),
  ('qb_vc_team_execution_3', 'vc_team_execution', 3, 'What execution mistake did you make — and what did you learn?'),
  ('qb_vc_team_execution_4', 'vc_team_execution', 4, 'Who makes technical vs commercial decisions?'),
  ('qb_vc_team_execution_5', 'vc_team_execution', 5, 'Which advisors materially influence outcomes?'),
  ('qb_vc_business_risks_1', 'vc_business_risks', 1, 'What are the top 3 reasons this business could fail?'),
  ('qb_vc_business_risks_2', 'vc_business_risks', 2, 'What assumptions keep you up at night?'),
  ('qb_vc_business_risks_3', 'vc_business_risks', 3, 'What dependency would hurt you most if removed?'),
  ('qb_vc_business_risks_4', 'vc_business_risks', 4, 'What external factors could slow adoption?'),
  ('qb_vc_business_risks_5', 'vc_business_risks', 5, 'What risk increases as you scale?'),
  ('qb_vc_business_attractiveness_1', 'vc_business_attractiveness', 1, 'If this works, how big can it realistically become?'),
  ('qb_vc_business_attractiveness_2', 'vc_business_attractiveness', 2, 'What makes this a venture-scale opportunity?'),
  ('qb_vc_business_attractiveness_3', 'vc_business_attractiveness', 3, 'Where do margins expand over time?'),
  ('qb_vc_business_attractiveness_4', 'vc_business_attractiveness', 4, 'What strategic buyers would care about this?'),
  ('qb_vc_business_attractiveness_5', 'vc_business_attractiveness', 5, 'Why could this become a category leader?'),
  ('qb_vc_climate_impact_1', 'vc_climate_impact', 1, 'What is the baseline scenario without your solution?'),
  ('qb_vc_climate_impact_2', 'vc_climate_impact', 2, 'What specific metric defines your climate impact?'),
  ('qb_vc_climate_impact_3', 'vc_climate_impact', 3, 'Is this impact reduction, avoidance, or removal?'),
  ('qb_vc_climate_impact_4', 'vc_climate_impact', 4, 'How is impact measured and verified?'),
  ('qb_vc_climate_impact_5', 'vc_climate_impact', 5, 'Would this impact happen without you (additionality)?'),
  ('qb_vc_climate_impact_6', 'vc_climate_impact', 6, 'What assumptions drive your impact estimates?'),
  ('qb_vc_climate_impact_7', 'vc_climate_impact', 7, 'What are potential rebound or leakage effects?'),
  ('qb_vc_climate_impact_8', 'vc_climate_impact', 8, 'How does this align with net-zero or 1.5°C pathways?'),
  ('qb_vc_storytelling_1', 'vc_storytelling', 1, 'What is the one thing you want us to remember?'),
  ('qb_vc_storytelling_2', 'vc_storytelling', 2, 'Why does this matter now?'),
  ('qb_vc_storytelling_3', 'vc_storytelling', 3, 'Which slide best represents your core insight?'),
  ('qb_vc_storytelling_4', 'vc_storytelling', 4, 'What would you remove if you had 5 slides fewer?'),
  ('qb_vc_storytelling_5', 'vc_storytelling', 5, 'Where do most people misunderstand your business?')
ON CONFLICT (id) DO NOTHING;
