-- W1-B · migration 5 of 13 (0025 – 0037).
--
-- Admin console → Organisation → Team & roles → **Task permissions**
-- (`admin/s-tm.html` + `permDefaults` in the admin script): 21 tasks × 5 roles
-- for the incubator workspace, 24 × 6 for the investor one — 249 rows.
--
-- GATE, NOT GRANT. `granted = 0` removes a capability the role would otherwise
-- have; `granted = 1` leaves the application's finer rules (pipeline transition
-- role lists, `requireRole`, stage gating) exactly as they are. That is what
-- lets this seed reproduce today's behaviour to the cell — `npm run roles`
-- stays 526 / 526 — while still making every cell worth toggling. W3-A, which
-- owns the runtime engine, must AND the permission with the existing rule
-- rather than replacing it.
--
-- SEED DERIVATION (mirrored, with the reasoning, in `src/shared/types.ts`
-- → PERMISSION_TASKS / DEFAULT_ROLE_PERMISSIONS; test/unit/permissions.test.ts
-- re-derives it from `nav.ts` + `pipeline/` and fails if the two drift):
--   • a task that maps to nav slugs / a pipeline action / a route is seeded to
--     the roles that can reach it in the shipped application TODAY;
--   • a task the prototype names but the product has no verb for — Reassign,
--     Remind, Activate / Deactivate / Delete user, Out-of-office delegation,
--     Register — is seeded to the prototype's own default column, since there
--     is nothing in the product to contradict.
--
-- WHERE THE TWO DISAGREE, TODAY'S APPLICATION WINS (plan §8). The prototype's
-- "Client admin" column has no Upload / Evaluate / Assign / Query; this
-- application's `admin` has had all four since Phase 1, and narrowing them here
-- would silently strip an existing capability and break the roles harness.
--
-- `founder` holds no row on purpose: founder isolation is a security invariant
-- the roles harness asserts (§B), not an administrator's toggle. `mentor` holds
-- none for the same reason it is absent from `Role` — a directory record with
-- no pipeline authority (commit 8822db2).

CREATE TABLE IF NOT EXISTS role_permissions (
  edition    TEXT NOT NULL CHECK (edition IN ('incubator', 'vc')),
  role       TEXT NOT NULL,
  task_id    TEXT NOT NULL,
  granted    INTEGER NOT NULL DEFAULT 0 CHECK (granted IN (0, 1)),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_by TEXT REFERENCES users (id),
  PRIMARY KEY (edition, role, task_id)
);
CREATE INDEX IF NOT EXISTS idx_role_permissions_lookup ON role_permissions (edition, role);

INSERT INTO role_permissions (edition, role, task_id, granted) VALUES
  ('incubator', 'superuser', 'register', 1),
  ('incubator', 'admin', 'register', 1),
  ('incubator', 'program_manager', 'register', 0),
  ('incubator', 'program_associate', 'register', 0),
  ('incubator', 'jury', 'register', 0),
  ('incubator', 'superuser', 'upgrade', 1),
  ('incubator', 'admin', 'upgrade', 1),
  ('incubator', 'program_manager', 'upgrade', 0),
  ('incubator', 'program_associate', 'upgrade', 0),
  ('incubator', 'jury', 'upgrade', 0),
  ('incubator', 'superuser', 'upload', 1),
  ('incubator', 'admin', 'upload', 1),
  ('incubator', 'program_manager', 'upload', 1),
  ('incubator', 'program_associate', 'upload', 1),
  ('incubator', 'jury', 'upload', 0),
  ('incubator', 'superuser', 'evaluate', 1),
  ('incubator', 'admin', 'evaluate', 1),
  ('incubator', 'program_manager', 'evaluate', 1),
  ('incubator', 'program_associate', 'evaluate', 1),
  ('incubator', 'jury', 'evaluate', 1),
  ('incubator', 'superuser', 'assign', 1),
  ('incubator', 'admin', 'assign', 1),
  ('incubator', 'program_manager', 'assign', 1),
  ('incubator', 'program_associate', 'assign', 1),
  ('incubator', 'jury', 'assign', 0),
  ('incubator', 'superuser', 'reassign', 1),
  ('incubator', 'admin', 'reassign', 0),
  ('incubator', 'program_manager', 'reassign', 1),
  ('incubator', 'program_associate', 'reassign', 0),
  ('incubator', 'jury', 'reassign', 0),
  ('incubator', 'superuser', 'remind', 1),
  ('incubator', 'admin', 'remind', 0),
  ('incubator', 'program_manager', 'remind', 1),
  ('incubator', 'program_associate', 'remind', 1),
  ('incubator', 'jury', 'remind', 0),
  ('incubator', 'superuser', 'query', 1),
  ('incubator', 'admin', 'query', 1),
  ('incubator', 'program_manager', 'query', 1),
  ('incubator', 'program_associate', 'query', 1),
  ('incubator', 'jury', 'query', 0),
  ('incubator', 'superuser', 'introcall', 1),
  ('incubator', 'admin', 'introcall', 1),
  ('incubator', 'program_manager', 'introcall', 1),
  ('incubator', 'program_associate', 'introcall', 1),
  ('incubator', 'jury', 'introcall', 1),
  ('incubator', 'superuser', 'jurypipeline', 1),
  ('incubator', 'admin', 'jurypipeline', 1),
  ('incubator', 'program_manager', 'jurypipeline', 1),
  ('incubator', 'program_associate', 'jurypipeline', 0),
  ('incubator', 'jury', 'jurypipeline', 1),
  ('incubator', 'superuser', 'shortlistsignup', 1),
  ('incubator', 'admin', 'shortlistsignup', 1),
  ('incubator', 'program_manager', 'shortlistsignup', 1),
  ('incubator', 'program_associate', 'shortlistsignup', 0),
  ('incubator', 'jury', 'shortlistsignup', 0),
  ('incubator', 'superuser', 'signuppipeline', 1),
  ('incubator', 'admin', 'signuppipeline', 1),
  ('incubator', 'program_manager', 'signuppipeline', 0),
  ('incubator', 'program_associate', 'signuppipeline', 1),
  ('incubator', 'jury', 'signuppipeline', 0),
  ('incubator', 'superuser', 'onboard', 1),
  ('incubator', 'admin', 'onboard', 1),
  ('incubator', 'program_manager', 'onboard', 0),
  ('incubator', 'program_associate', 'onboard', 1),
  ('incubator', 'jury', 'onboard', 0),
  ('incubator', 'superuser', 'archive', 1),
  ('incubator', 'admin', 'archive', 1),
  ('incubator', 'program_manager', 'archive', 1),
  ('incubator', 'program_associate', 'archive', 1),
  ('incubator', 'jury', 'archive', 1),
  ('incubator', 'superuser', 'activateuser', 1),
  ('incubator', 'admin', 'activateuser', 1),
  ('incubator', 'program_manager', 'activateuser', 1),
  ('incubator', 'program_associate', 'activateuser', 0),
  ('incubator', 'jury', 'activateuser', 0),
  ('incubator', 'superuser', 'deactivateuser', 1),
  ('incubator', 'admin', 'deactivateuser', 1),
  ('incubator', 'program_manager', 'deactivateuser', 1),
  ('incubator', 'program_associate', 'deactivateuser', 0),
  ('incubator', 'jury', 'deactivateuser', 0),
  ('incubator', 'superuser', 'deleteuser', 1),
  ('incubator', 'admin', 'deleteuser', 1),
  ('incubator', 'program_manager', 'deleteuser', 0),
  ('incubator', 'program_associate', 'deleteuser', 0),
  ('incubator', 'jury', 'deleteuser', 0),
  ('incubator', 'superuser', 'configparams', 1),
  ('incubator', 'admin', 'configparams', 1),
  ('incubator', 'program_manager', 'configparams', 0),
  ('incubator', 'program_associate', 'configparams', 0),
  ('incubator', 'jury', 'configparams', 0),
  ('incubator', 'superuser', 'adminconsole', 1),
  ('incubator', 'admin', 'adminconsole', 1),
  ('incubator', 'program_manager', 'adminconsole', 0),
  ('incubator', 'program_associate', 'adminconsole', 0),
  ('incubator', 'jury', 'adminconsole', 0),
  ('incubator', 'superuser', 'addmembers', 1),
  ('incubator', 'admin', 'addmembers', 1),
  ('incubator', 'program_manager', 'addmembers', 0),
  ('incubator', 'program_associate', 'addmembers', 0),
  ('incubator', 'jury', 'addmembers', 0),
  ('incubator', 'superuser', 'outofofficedelegation', 1),
  ('incubator', 'admin', 'outofofficedelegation', 1),
  ('incubator', 'program_manager', 'outofofficedelegation', 1),
  ('incubator', 'program_associate', 'outofofficedelegation', 0),
  ('incubator', 'jury', 'outofofficedelegation', 0),
  ('vc', 'superuser', 'register', 1),
  ('vc', 'admin', 'register', 1),
  ('vc', 'partner', 'register', 0),
  ('vc', 'ic_member', 'register', 0),
  ('vc', 'associate', 'register', 0),
  ('vc', 'analyst', 'register', 0),
  ('vc', 'superuser', 'upgrade', 1),
  ('vc', 'admin', 'upgrade', 1),
  ('vc', 'partner', 'upgrade', 0),
  ('vc', 'ic_member', 'upgrade', 0),
  ('vc', 'associate', 'upgrade', 0),
  ('vc', 'analyst', 'upgrade', 0),
  ('vc', 'superuser', 'upload', 1),
  ('vc', 'admin', 'upload', 1),
  ('vc', 'partner', 'upload', 1),
  ('vc', 'ic_member', 'upload', 0),
  ('vc', 'associate', 'upload', 1),
  ('vc', 'analyst', 'upload', 1),
  ('vc', 'superuser', 'evaluate', 1),
  ('vc', 'admin', 'evaluate', 1),
  ('vc', 'partner', 'evaluate', 1),
  ('vc', 'ic_member', 'evaluate', 1),
  ('vc', 'associate', 'evaluate', 1),
  ('vc', 'analyst', 'evaluate', 1),
  ('vc', 'superuser', 'assign', 1),
  ('vc', 'admin', 'assign', 1),
  ('vc', 'partner', 'assign', 0),
  ('vc', 'ic_member', 'assign', 0),
  ('vc', 'associate', 'assign', 1),
  ('vc', 'analyst', 'assign', 1),
  ('vc', 'superuser', 'reassign', 1),
  ('vc', 'admin', 'reassign', 0),
  ('vc', 'partner', 'reassign', 1),
  ('vc', 'ic_member', 'reassign', 0),
  ('vc', 'associate', 'reassign', 1),
  ('vc', 'analyst', 'reassign', 0),
  ('vc', 'superuser', 'remind', 1),
  ('vc', 'admin', 'remind', 0),
  ('vc', 'partner', 'remind', 1),
  ('vc', 'ic_member', 'remind', 0),
  ('vc', 'associate', 'remind', 1),
  ('vc', 'analyst', 'remind', 1),
  ('vc', 'superuser', 'query', 1),
  ('vc', 'admin', 'query', 1),
  ('vc', 'partner', 'query', 0),
  ('vc', 'ic_member', 'query', 0),
  ('vc', 'associate', 'query', 1),
  ('vc', 'analyst', 'query', 1),
  ('vc', 'superuser', 'introcall', 1),
  ('vc', 'admin', 'introcall', 1),
  ('vc', 'partner', 'introcall', 1),
  ('vc', 'ic_member', 'introcall', 1),
  ('vc', 'associate', 'introcall', 1),
  ('vc', 'analyst', 'introcall', 1),
  ('vc', 'superuser', 'assocpipeline', 1),
  ('vc', 'admin', 'assocpipeline', 1),
  ('vc', 'partner', 'assocpipeline', 0),
  ('vc', 'ic_member', 'assocpipeline', 0),
  ('vc', 'associate', 'assocpipeline', 1),
  ('vc', 'analyst', 'assocpipeline', 0),
  ('vc', 'superuser', 'partnerpipeline', 1),
  ('vc', 'admin', 'partnerpipeline', 1),
  ('vc', 'partner', 'partnerpipeline', 1),
  ('vc', 'ic_member', 'partnerpipeline', 1),
  ('vc', 'associate', 'partnerpipeline', 0),
  ('vc', 'analyst', 'partnerpipeline', 0),
  ('vc', 'superuser', 'icpipeline', 1),
  ('vc', 'admin', 'icpipeline', 1),
  ('vc', 'partner', 'icpipeline', 0),
  ('vc', 'ic_member', 'icpipeline', 1),
  ('vc', 'associate', 'icpipeline', 0),
  ('vc', 'analyst', 'icpipeline', 0),
  ('vc', 'superuser', 'mpapproval', 1),
  ('vc', 'admin', 'mpapproval', 0),
  ('vc', 'partner', 'mpapproval', 1),
  ('vc', 'ic_member', 'mpapproval', 0),
  ('vc', 'associate', 'mpapproval', 0),
  ('vc', 'analyst', 'mpapproval', 0),
  ('vc', 'superuser', 'openchecklist', 1),
  ('vc', 'admin', 'openchecklist', 1),
  ('vc', 'partner', 'openchecklist', 1),
  ('vc', 'ic_member', 'openchecklist', 1),
  ('vc', 'associate', 'openchecklist', 0),
  ('vc', 'analyst', 'openchecklist', 0),
  ('vc', 'superuser', 'signup', 1),
  ('vc', 'admin', 'signup', 1),
  ('vc', 'partner', 'signup', 1),
  ('vc', 'ic_member', 'signup', 0),
  ('vc', 'associate', 'signup', 0),
  ('vc', 'analyst', 'signup', 0),
  ('vc', 'superuser', 'onboard', 1),
  ('vc', 'admin', 'onboard', 1),
  ('vc', 'partner', 'onboard', 1),
  ('vc', 'ic_member', 'onboard', 1),
  ('vc', 'associate', 'onboard', 0),
  ('vc', 'analyst', 'onboard', 0),
  ('vc', 'superuser', 'archive', 1),
  ('vc', 'admin', 'archive', 1),
  ('vc', 'partner', 'archive', 1),
  ('vc', 'ic_member', 'archive', 1),
  ('vc', 'associate', 'archive', 1),
  ('vc', 'analyst', 'archive', 1),
  ('vc', 'superuser', 'activateuser', 1),
  ('vc', 'admin', 'activateuser', 1),
  ('vc', 'partner', 'activateuser', 1),
  ('vc', 'ic_member', 'activateuser', 0),
  ('vc', 'associate', 'activateuser', 1),
  ('vc', 'analyst', 'activateuser', 0),
  ('vc', 'superuser', 'deactivateuser', 1),
  ('vc', 'admin', 'deactivateuser', 1),
  ('vc', 'partner', 'deactivateuser', 1),
  ('vc', 'ic_member', 'deactivateuser', 0),
  ('vc', 'associate', 'deactivateuser', 1),
  ('vc', 'analyst', 'deactivateuser', 0),
  ('vc', 'superuser', 'deleteuser', 1),
  ('vc', 'admin', 'deleteuser', 1),
  ('vc', 'partner', 'deleteuser', 0),
  ('vc', 'ic_member', 'deleteuser', 0),
  ('vc', 'associate', 'deleteuser', 0),
  ('vc', 'analyst', 'deleteuser', 0),
  ('vc', 'superuser', 'configparams', 1),
  ('vc', 'admin', 'configparams', 1),
  ('vc', 'partner', 'configparams', 0),
  ('vc', 'ic_member', 'configparams', 0),
  ('vc', 'associate', 'configparams', 0),
  ('vc', 'analyst', 'configparams', 0),
  ('vc', 'superuser', 'adminconsole', 1),
  ('vc', 'admin', 'adminconsole', 1),
  ('vc', 'partner', 'adminconsole', 0),
  ('vc', 'ic_member', 'adminconsole', 0),
  ('vc', 'associate', 'adminconsole', 0),
  ('vc', 'analyst', 'adminconsole', 0),
  ('vc', 'superuser', 'addmembers', 1),
  ('vc', 'admin', 'addmembers', 1),
  ('vc', 'partner', 'addmembers', 0),
  ('vc', 'ic_member', 'addmembers', 0),
  ('vc', 'associate', 'addmembers', 0),
  ('vc', 'analyst', 'addmembers', 0),
  ('vc', 'superuser', 'outofofficedelegation', 1),
  ('vc', 'admin', 'outofofficedelegation', 1),
  ('vc', 'partner', 'outofofficedelegation', 1),
  ('vc', 'ic_member', 'outofofficedelegation', 0),
  ('vc', 'associate', 'outofofficedelegation', 1),
  ('vc', 'analyst', 'outofofficedelegation', 0)
ON CONFLICT (edition, role, task_id) DO NOTHING;
