import type { PipelineConfig } from "./types";

// VC pipeline — mirrors AISJ_VC_eval_roleflow_v2. superuser = Managing Partner
// (full discretion). "Return to Partner" and "another meeting" loop back to
// partner_review rather than introducing separate stages.
export const vcPipeline: PipelineConfig = {
  edition: "vc",
  initialStage: "uploaded",
  stages: [
    { id: "uploaded", label: "Uploaded", kind: "intake" },
    { id: "pending_ai", label: "Pending AI", kind: "intake" },
    { id: "analyst_scoring", label: "Analyst Scoring", kind: "evaluation" },
    { id: "associate_review", label: "Associate Review", kind: "evaluation" },
    { id: "partner_review", label: "Partner Review", kind: "evaluation" },
    { id: "partner_call", label: "Partner Call", kind: "decision" },
    { id: "investment_dd", label: "Investment DD", kind: "evaluation" },
    { id: "ic_review", label: "IC Review", kind: "decision" },
    { id: "mp_decision", label: "Managing Partner Decision", kind: "decision" },
    { id: "alignment_call", label: "Alignment Call", kind: "decision" },
    { id: "term_sheet", label: "Term Sheet", kind: "advancing" },
    { id: "legal_dd", label: "Legal DD", kind: "advancing" },
    { id: "onboard_ready", label: "Onboard Ready", kind: "advancing", terminal: true },
    { id: "archived", label: "Archived", kind: "exit", terminal: true },
  ],
  transitions: [
    {
      from: "uploaded",
      to: "pending_ai",
      action: "submit_for_ai",
      label: "Submit for AI evaluation",
      roles: ["analyst", "associate", "admin", "superuser"],
    },
    {
      from: "pending_ai",
      to: "analyst_scoring",
      action: "ai_complete",
      label: "AI evaluation complete",
      roles: ["analyst", "admin", "superuser"],
    },
    {
      from: "analyst_scoring",
      to: "associate_review",
      action: "submit_core_scores",
      label: "Submit core scores",
      roles: ["analyst", "associate", "admin", "superuser"],
    },
    {
      from: "associate_review",
      to: "partner_review",
      action: "shortlist_to_partner",
      label: "Shortlist to partner",
      roles: ["associate", "admin", "superuser"],
    },
    {
      from: "associate_review",
      to: "archived",
      action: "not_shortlisted",
      label: "Not shortlisted",
      roles: ["associate", "partner", "admin", "superuser"],
    },
    {
      from: "partner_review",
      to: "partner_call",
      action: "advance_to_call",
      label: "Advance to partner call",
      roles: ["partner", "admin", "superuser"],
    },
    {
      from: "partner_review",
      to: "archived",
      action: "not_shortlisted_partner",
      label: "Not shortlisted",
      roles: ["partner", "admin", "superuser"],
    },
    {
      from: "partner_call",
      to: "investment_dd",
      action: "sponsor_to_ic",
      label: "Sponsor to IC",
      roles: ["partner", "superuser"],
    },
    {
      from: "partner_call",
      to: "archived",
      action: "pass_at_call",
      label: "Pass",
      roles: ["partner", "superuser"],
    },
    {
      from: "partner_call",
      to: "partner_review",
      action: "another_meeting",
      label: "Need another meeting",
      roles: ["partner", "superuser"],
    },
    {
      from: "investment_dd",
      to: "ic_review",
      action: "mp_approve_dd",
      label: "Approve for IC",
      roles: ["partner", "superuser"],
    },
    {
      from: "ic_review",
      to: "mp_decision",
      action: "close_ic_vote",
      label: "Close IC vote",
      roles: ["superuser"],
    },
    {
      from: "mp_decision",
      to: "alignment_call",
      action: "invest",
      label: "Invest",
      roles: ["superuser"],
    },
    {
      from: "mp_decision",
      to: "archived",
      action: "pass",
      label: "Pass",
      roles: ["superuser"],
    },
    {
      from: "mp_decision",
      to: "partner_review",
      action: "return_to_partner",
      label: "Return to partner",
      roles: ["superuser"],
    },
    {
      from: "alignment_call",
      to: "term_sheet",
      action: "issue_term_sheet",
      label: "Issue term sheet",
      roles: ["partner", "superuser"],
    },
    {
      from: "term_sheet",
      to: "legal_dd",
      action: "start_legal_dd",
      label: "Start legal DD",
      roles: ["partner", "superuser"],
    },
    {
      from: "legal_dd",
      to: "onboard_ready",
      action: "complete_legal_dd",
      label: "Complete legal DD",
      roles: ["admin", "superuser"],
    },
  ],
};
